name: Chess

on:
  issues:
    types: [opened]

jobs:
  move:
    name: Play Chess
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, 'Chess:')
    
    steps:
      - uses: actions/checkout@v4

      # Set up a Python 3.8 (64-bit) instance
      - name: Setting up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.8"
          architecture: "x64"

      # Use pip to install the dependencies and then run the script
      - name: Play chess
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          GITHUB_TOKEN: ${{ secrets.CHESS_TOKEN }}
          REPOSITORY_OWNER: ${{ github.repository_owner }}
        run: |
          pip install -r requirements.txt
          python main.py

      # Create new commit with the changed files and push it to GitHub
      - name: Commit and push changes
        env:
          ISSUE_TITLE: ${{ github.event.issue.title }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "${ISSUE_TITLE} by ${{ github.event.issue.user.login }}"
          git push
